import { Component, OnInit } from '@angular/core';
import { MovieCategory } from './movie-category';

@Component({
  selector: 'mm-movie-list',
  templateUrl: './movie-list.component.html',
  styleUrls: ['./movie-list.component.css'],
})
export class MovieListComponent implements OnInit {
  movieCategories: MovieCategory[] = [
    {
      title: 'Latest',
      tag: 'latest',
      movies: [
        {
          backdrop_path: '/lNyLSOKMMeUPr1RsL4KcRuIXwHt.jpg',
          id: 580489,
          original_language: 'en',
          original_title: 'Venom: Let There Be Carnage',
          overview:
            'After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.',
          popularity: 4293.383,
          poster_path: '/rjkmN1dniUHVYAtwuV3Tji7FsDO.jpg',
          release_date: '2021-09-30',
          title: 'Venom: Let There Be Carnage',
          video: false,
          vote_average: 6.8,
          vote_count: 1798,
        },
        {
          backdrop_path: '/eeijXm3553xvuFbkPFkDG6CLCbQ.jpg',
          id: 438631,
          original_language: 'en',
          original_title: 'Dune',
          overview:
            "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
          popularity: 2264.439,
          poster_path: '/d5NXSklXo0qyIYkgV94XAgMIckC.jpg',
          release_date: '2021-09-15',
          title: 'Dune',
          video: false,
          vote_average: 8,
          vote_count: 3716,
        },
        {
          backdrop_path: '/fzKWwcaam9QSTaMSJlORuSojxio.jpg',
          id: 524434,
          original_language: 'en',
          original_title: 'Eternals',
          overview:
            'The Eternals are a team of ancient aliens who have been living on Earth in secret for thousands of years. When an unexpected tragedy forces them out of the shadows, they are forced to reunite against mankind’s most ancient enemy, the Deviants.',
          popularity: 2462.242,
          poster_path: '/6AdXwFTRTAzggD2QUTt5B7JFGKL.jpg',
          release_date: '2021-11-03',
          title: 'Eternals',
          video: false,
          vote_average: 7.1,
          vote_count: 739,
        },
        {
          backdrop_path: '/mu8RKavbv7Ml48twHQ6XVk7zw8e.jpg',
          id: 796499,
          original_language: 'en',
          original_title: 'Army of Thieves',
          overview:
            'A mysterious woman recruits bank teller Ludwig Dieter to lead a group of aspiring thieves on a top-secret heist during the early stages of the zombie apocalypse.',
          popularity: 2654.451,
          poster_path: '/j04Oepj3LGTWSb1ltXm0pcy50Xq.jpg',
          release_date: '2021-10-27',
          title: 'Army of Thieves',
          video: false,
          vote_average: 6.9,
          vote_count: 590,
        },
        {
          backdrop_path: '/cinER0ESG0eJ49kXlExM0MEWGxW.jpg',
          id: 566525,
          original_language: 'en',
          original_title: 'Shang-Chi and the Legend of the Ten Rings',
          overview:
            'Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.',
          popularity: 2601.273,
          poster_path: '/xeItgLK9qcafxbd8kYgv7XnMEog.jpg',
          release_date: '2021-09-01',
          title: 'Shang-Chi and the Legend of the Ten Rings',
          video: false,
          vote_average: 7.8,
          vote_count: 1726,
        },
        {
          backdrop_path: '/8Y43POKjjKDGI9MH89NW0NAzzp8.jpg',
          id: 550988,
          original_language: 'en',
          original_title: 'Free Guy',
          overview:
            'A bank teller called Guy realizes he is a background character in an open world video game called Free City that will soon go offline.',
          popularity: 1576.431,
          poster_path: '/xmbU4JTUm8rsdtn7Y3Fcm30GpeT.jpg',
          release_date: '2021-08-11',
          title: 'Free Guy',
          video: false,
          vote_average: 7.8,
          vote_count: 3536,
        },
        {
          backdrop_path: '/u5Fp9GBy9W8fqkuGfLBuuoJf57Z.jpg',
          id: 370172,
          original_language: 'en',
          original_title: 'No Time to Die',
          overview:
            'Bond has left active service and is enjoying a tranquil life in Jamaica. His peace is short-lived when his old friend Felix Leiter from the CIA turns up asking for help. The mission to rescue a kidnapped scientist turns out to be far more treacherous than expected, leading Bond onto the trail of a mysterious villain armed with dangerous new technology.',
          popularity: 1184.338,
          poster_path: '/iUgygt3fscRoKWCV1d0C7FbM9TP.jpg',
          release_date: '2021-09-29',
          title: 'No Time to Die',
          video: false,
          vote_average: 7.5,
          vote_count: 1399,
        },
        {
          backdrop_path: '/hugKriLPeBm3lErSCQiFOgQzpkC.jpg',
          id: 574060,
          original_language: 'en',
          original_title: 'Gunpowder Milkshake',
          overview:
            'In her turbulent life as a professional assassin, Sam has no choice but to go rogue to save the life of an innocent 8-year-old girl in the middle of the gang war she has unleashed.',
          popularity: 1094.568,
          poster_path: '/5AaKulwpUtkscAokKWtLenGTfVS.jpg',
          release_date: '2021-07-14',
          title: 'Gunpowder Milkshake',
          video: false,
          vote_average: 6.5,
          vote_count: 350,
        },
        {
          backdrop_path: '/oE6bhqqVFyIECtBzqIuvh6JdaB5.jpg',
          id: 522402,
          original_language: 'en',
          original_title: 'Finch',
          overview:
            "On a post-apocalyptic Earth, a robot, built to protect the life of his dying creator's beloved dog, learns about life, love, friendship, and what it means to be human.",
          popularity: 1077.773,
          poster_path: '/jKuDyqx7jrjiR9cDzB5pxzhJAdv.jpg',
          release_date: '2021-11-04',
          title: 'Finch',
          video: false,
          vote_average: 8.1,
          vote_count: 639,
        },
        {
          backdrop_path: '/VuukZLgaCrho2Ar8Scl9HtV3yD.jpg',
          id: 335983,
          original_language: 'en',
          original_title: 'Venom',
          overview:
            'Investigative journalist Eddie Brock attempts a comeback following a scandal, but accidentally becomes the host of Venom, a violent, super powerful alien symbiote. Soon, he must rely on his newfound powers to protect the world from a shadowy organization looking for a symbiote of their own.',
          popularity: 953.538,
          poster_path: '/2uNW4WbgBXL25BAbXGLnLqX71Sw.jpg',
          release_date: '2018-09-28',
          title: 'Venom',
          video: false,
          vote_average: 6.8,
          vote_count: 12144,
        },
        {
          backdrop_path: '/6xCOWFIb1Za7jeP6rqw7SfPgkNX.jpg',
          id: 768449,
          original_language: 'en',
          original_title: 'American Badger',
          overview:
            'A seemingly cold-blooded hitman is assigned to befriend a call girl, but all hell breaks loose when he is assigned to kill her.',
          popularity: 943.442,
          poster_path: '/8mO2ZTTOnLnaEQd1sNZAE2XBoOg.jpg',
          release_date: '2021-03-05',
          title: 'American Badger',
          video: false,
          vote_average: 6.3,
          vote_count: 14,
        },
      ],
    },
    {
      title: 'Top Rated',
      tag: 'top_rated',
      movies: [
        {
          "backdrop_path": "/5hNcsnMkwU2LknLoru73c76el3z.jpg",
          "id": 19404,
          "original_language": "hi",
          "original_title": "दिलवाले दुल्हनिया ले जायेंगे",
          "overview": "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
          "popularity": 27.72,
          "poster_path": "/2CAL2433ZeIihfX1Hb2139CX0pW.jpg",
          "release_date": "1995-10-20",
          "title": "Dilwale Dulhania Le Jayenge",
          "video": false,
          "vote_average": 8.7,
          "vote_count": 3215
          },
          {
          "backdrop_path": "/iNh3BivHyg5sQRPP1KOkzguEX0H.jpg",
          "id": 278,
          "original_language": "en",
          "original_title": "The Shawshank Redemption",
          "overview": "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
          "popularity": 63.357,
          "poster_path": "/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
          "release_date": "1994-09-23",
          "title": "The Shawshank Redemption",
          "video": false,
          "vote_average": 8.7,
          "vote_count": 20082
          },
          {
          "backdrop_path": "/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg",
          "id": 238,
          "original_language": "en",
          "original_title": "The Godfather",
          "overview": "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
          "popularity": 55.854,
          "poster_path": "/eEslKSwcqmiNS6va24Pbxf2UKmJ.jpg",
          "release_date": "1972-03-14",
          "title": "The Godfather",
          "video": false,
          "vote_average": 8.7,
          "vote_count": 15045
          },
          {
          "backdrop_path": "/jtAI6OJIWLWiRItNSZoWjrsUtmi.jpg",
          "id": 724089,
          "original_language": "en",
          "original_title": "Gabriel's Inferno Part II",
          "overview": "Professor Gabriel Emerson finally learns the truth about Julia Mitchell's identity, but his realization comes a moment too late. Julia is done waiting for the well-respected Dante specialist to remember her and wants nothing more to do with him. Can Gabriel win back her heart before she finds love in another's arms?",
          "popularity": 8.818,
          "poster_path": "/x5o8cLZfEXMoZczTYWLrUo1P7UJ.jpg",
          "release_date": "2020-07-31",
          "title": "Gabriel's Inferno Part II",
          "video": false,
          "vote_average": 8.7,
          "vote_count": 1320
          },
          {
          "backdrop_path": "/fQq1FWp1rC89xDrRMuyFJdFUdMd.jpg",
          "id": 761053,
          "original_language": "en",
          "original_title": "Gabriel's Inferno Part III",
          "overview": "The final part of the film adaption of the erotic romance novel Gabriel's Inferno written by an anonymous Canadian author under the pen name Sylvain Reynard.",
          "popularity": 26.744,
          "poster_path": "/qtX2Fg9MTmrbgN1UUvGoCsImTM8.jpg",
          "release_date": "2020-11-19",
          "title": "Gabriel's Inferno Part III",
          "video": false,
          "vote_average": 8.6,
          "vote_count": 889
          },
          {
          "backdrop_path": "/w2uGvCpMtvRqZg6waC1hvLyZoJa.jpg",
          "id": 696374,
          "original_language": "en",
          "original_title": "Gabriel's Inferno",
          "overview": "An intriguing and sinful exploration of seduction, forbidden love, and redemption, Gabriel's Inferno is a captivating and wildly passionate tale of one man's escape from his own personal hell as he tries to earn the impossible--forgiveness and love.",
          "popularity": 10.413,
          "poster_path": "/oyG9TL7FcRP4EZ9Vid6uKzwdndz.jpg",
          "release_date": "2020-05-29",
          "title": "Gabriel's Inferno",
          "video": false,
          "vote_average": 8.6,
          "vote_count": 2140
          },
          {
          "backdrop_path": "/loRmRzQXZeqG78TqZuyvSlEQfZb.jpg",
          "id": 424,
          "original_language": "en",
          "original_title": "Schindler's List",
          "overview": "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
          "popularity": 43.408,
          "poster_path": "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
          "release_date": "1993-11-30",
          "title": "Schindler's List",
          "video": false,
          "vote_average": 8.6,
          "vote_count": 12007
          },
          {
          "backdrop_path": "/1EAxNqdkVnp48a7NUuNBHGflowM.jpg",
          "id": 283566,
          "original_language": "ja",
          "original_title": "シン・エヴァンゲリオン劇場版:||",
          "overview": "In the aftermath of the Fourth Impact, stranded without their Evangelions, Shinji, Asuka, and Rei find refuge in one of the rare pockets of humanity that still exist on the ruined planet Earth. There, each of them live a life far different from their days as an Evangelion pilot. However, the danger to the world is far from over. A new impact is looming on the horizon—one that will prove to be the true end of Evangelion.",
          "popularity": 199.267,
          "poster_path": "/jDwZavHo99JtGsCyRzp4epeeBHx.jpg",
          "release_date": "2021-03-08",
          "title": "Evangelion: 3.0+1.0 Thrice Upon a Time",
          "video": false,
          "vote_average": 8.6,
          "vote_count": 366
          },
          {
          "backdrop_path": "/poec6RqOKY9iSiIUmfyfPfiLtvB.jpg",
          "id": 240,
          "original_language": "en",
          "original_title": "The Godfather: Part II",
          "overview": "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
          "popularity": 37.31,
          "poster_path": "/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
          "release_date": "1974-12-20",
          "title": "The Godfather: Part II",
          "video": false,
          "vote_average": 8.6,
          "vote_count": 9042
          },
          {
          "backdrop_path": "/l5K9elugftlcyIHHm4nylvsn26X.jpg",
          "id": 255709,
          "original_language": "ko",
          "original_title": "소원",
          "overview": "After 8-year-old So-won narrowly survives a brutal sexual assault, her family labors to help her heal while coping with their own rage and grief.",
          "popularity": 6.968,
          "poster_path": "/x9yjkm9gIz5qI5fJMUTfBnWiB2o.jpg",
          "release_date": "2013-10-02",
          "title": "Hope",
          "video": false,
          "vote_average": 8.6,
          "vote_count": 226
          },
      ]
    }
  ];

  constructor() {}

  ngOnInit(): void {}
}
